all: prac8 

prac8: shell.c vdisk.o funciones_bajo_nivel.h DateManagement.h BlockManagement.h funciones_alto_nivel.h iNodeManagement.h funciones_alto_nivel_dir.h
     gcc -o shell  shell.c vdisk.o funciones_bajo_nivel.h DateManagement.h BlockManagement.h funciones_alto_nivel.h iNodeManagement.h funciones_alto_nivel_dir.h -I.